language: node_js
node_js:
- node
- lts/boron
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email:
    on_success: never
deploy:
  provider: npm
  email: r.gautamkrishna@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
    repo: gautamkrishnar/naughtychecker.js
